package com.example.gamesphere.repository;

import androidx.annotation.NonNull;
import com.example.gamesphere.model.User;
import com.google.android.gms.tasks.Task;
import com.google.android.gms.tasks.TaskCompletionSource;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.Query;
import com.google.firebase.database.ValueEventListener;
import java.util.HashMap;
import java.util.Map;

/**
 * The class interacts with User realtime table.
 * Operations such as: insertUser, getUserByUid, checkUsernameExists, etc.
 */
public class UserRepository {

    private final DatabaseReference userRef;
    public UserRepository()
    {
        userRef = FirebaseDatabase.getInstance().getReference("User");  // reference to the table
    }

    /**
     * Asynchronous function which inserts a new user into User table.
     * @param firebaseUser  the user, as previously created in Authentication
     * @param username      the username (as required by user)
     * @param isAdmin       true if the user is administrator, otherwise- false.
     * @param callback  callback  the result is not immediate, callback will consist the result as soon as
     *                  there is one. (when the listener was informed that the mission completed)
     *                  returns the User object, otherwise- exception.
     */
    public void insertUser(FirebaseUser firebaseUser, String username, boolean isAdmin, OnUserInsertedCallback callback)
    {
        if (firebaseUser != null || username != null) // user was already created in Firebase Authentication
        {
            DatabaseReference myRef = userRef.child(username); // get the row in User
            assert firebaseUser != null;
            firebaseUser.getUid();  // get the uid from Authentication

            // Create a User object
            User user = new User(firebaseUser.getUid(), username, isAdmin);

            // Insert user into User table
            myRef.setValue(user)
                    .addOnSuccessListener(aVoid -> {
                        callback.onSuccess(user); // Pass user back to the caller
                    })
                    .addOnFailureListener(callback::onFailure);
        }
    }

    /**
     * Asynchronous function which fetches the User object, corresponding to the given uid.
     * (the uid was generated by Authentication)
     * @param uid   the required uid (as generated in Authentication)
     * @return task result (User object, or null if not found, or exception)
     */
    public Task<User> getUserByUid(String uid)
    {
        // Create a TaskCompletionSource to manage the Task
        TaskCompletionSource<User> taskCompletionSource = new TaskCompletionSource<>();

        Query userQuery = userRef.orderByChild("uid").equalTo(uid); // Find the user with the given uid
        // a listener to handle the query result
        userQuery.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                if (dataSnapshot.exists()) {
                    // Get the first (and only) child directly (uid is unique in User table)
                    DataSnapshot userSnapshot = dataSnapshot.getChildren().iterator().next();
                    User user = userSnapshot.getValue(User.class);
                    taskCompletionSource.setResult(user);
                } else {
                    // No user found with the given uid, set result as null
                    taskCompletionSource.setResult(null);
                }
            }
            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {
                // If the query is cancelled or fails, set task as failed
                taskCompletionSource.setException(databaseError.toException());
            }
        });
        return taskCompletionSource.getTask();
    }

    /**
     * Asynchronous function which checks if the given username already exists.
     * @param username the username to check
     * @return task result (true- if exists, otherwise- false)
     */
    public Task<Boolean> checkUsernameExists(String username)
    {
        // Create a TaskCompletionSource to manage the Task
        TaskCompletionSource<Boolean> taskCompletionSource = new TaskCompletionSource<>();

        Query query = userRef.orderByChild("username").equalTo(username); // get the row in User
        // a listener to handle the query result
        query.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                // Check if the username exists in the database
                boolean usernameExists = dataSnapshot.exists();
                // Set the result
                taskCompletionSource.setResult(usernameExists);
            }
            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {
                taskCompletionSource.setException(databaseError.toException());
            }
        });
        return taskCompletionSource.getTask();
    }

    /**
     * Asynchronous function which handles username modification, on User table (only)
     * Removes old item on User, and inserts a new item instead (since items are grouped under the old username)
     * @param firebaseUser  the current logged in user
     * @param user          User object (with old username)
     * @param newUsername   new username to set
     * @param callback  callback  the result is not immediate, callback will consist the result as soon as
     *                  there is one. (when the listener was informed that the mission completed)
     *                  if an error occurred- return exception.
     */
    public void updateUsername(FirebaseUser firebaseUser, User user, String newUsername, OnUpdateUsernameCallback callback)
    {
        DatabaseReference databaseRef = FirebaseDatabase.getInstance().getReference();

        // Removes old item on User, and inserts a new item instead (since items are grouped under the old username)
        String currentUsername = user.getUsername();
        String currentPath = "User/" + currentUsername;
        String newPath = "User/" + newUsername;

        // Prepare the updated user data
        Map<String, Object> updatedUserData = new HashMap<>();
        updatedUserData.put("username", newUsername);
        updatedUserData.put("uid", firebaseUser.getUid());
        updatedUserData.put("admin", user.isAdmin());

        // Update to the new path
        databaseRef.child(newPath).setValue(updatedUserData)
                .addOnSuccessListener(aVoid -> {
                    // Remove old entry if the username changed
                    if (!currentUsername.equals(newUsername)) {
                        databaseRef.child(currentPath).removeValue()
                                .addOnSuccessListener(v -> callback.onSuccess())
                                .addOnFailureListener(callback::onFailure);
                    } else {
                        callback.onSuccess();
                    }
                })
                .addOnFailureListener(callback::onFailure);
    }

    /**
     * Interface for OnUserInsertedCallback callback
     */
    public interface OnUserInsertedCallback {
        void onSuccess(User user);
        void onFailure(Exception e);
    }

    /**
     * Interface for OnUpdateUsernameCallback callback
     */
    public interface OnUpdateUsernameCallback {
        void onSuccess();
        void onFailure(Exception e);
    }

}
